// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAllfPmLJL3lt4ireqAw1N0ARHY3xWvUO0',
    appId: '1:287725636744:web:032edf838909a7099da33d',
    messagingSenderId: '287725636744',
    projectId: 'socialskills-66a88',
    authDomain: 'socialskills-66a88.firebaseapp.com',
    storageBucket: 'socialskills-66a88.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjTTTCJoCLNYXXYrkoDUWZJRSlBTwwB6s',
    appId: '1:287725636744:android:7e2312254a8272599da33d',
    messagingSenderId: '287725636744',
    projectId: 'socialskills-66a88',
    storageBucket: 'socialskills-66a88.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2JAeZFAlo0Jcvz_4hDHnIbvb2y0PCLME',
    appId: '1:287725636744:ios:8941df7641628ce69da33d',
    messagingSenderId: '287725636744',
    projectId: 'socialskills-66a88',
    storageBucket: 'socialskills-66a88.appspot.com',
    iosBundleId: 'com.example.socialskills',
  );
}
